- name: Package OpenWrt Firmware
  uses: unifreq/openwrt_packit@master
  env:
    OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
    PACKAGE_SOC: all
    KERNEL_VERSION_NAME: 6.1.50
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
